version: "3.0"

services:
  clothing-price-comparator:
    image: clothing-price-comparator-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - logs_d:/var/logs
    env_file:
      - ./.env.development
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo_d:/data/db
    ports:
      - 27017:27017
volumes:
  mongo_d:
  logs_d:
